<?php return array(
    'root' => array(
        'name' => 'typo3-console/libs',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'faa5ec872c014038cdd8594c5f8f8fae94e0c9db',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'helhum/config-loader' => array(
            'pretty_version' => 'v0.12.5',
            'version' => '0.12.5.0',
            'reference' => 'f761ab3fcf888b9d17d679d94b14aca24fe6bfab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../helhum/config-loader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.2.8',
            'version' => '6.2.8.0',
            'reference' => '75ed64103df4f6615e15a7fe38b8111099f47416',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typo3-console/libs' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'faa5ec872c014038cdd8594c5f8f8fae94e0c9db',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
