<?php return array(
    'root' => array(
        'name' => 'typo3-console/libs',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '2e06dc49b9d5a3f775e0a4e346646ffe5a181463',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'helhum/config-loader' => array(
            'pretty_version' => 'v0.12.5',
            'version' => '0.12.5.0',
            'reference' => 'f761ab3fcf888b9d17d679d94b14aca24fe6bfab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../helhum/config-loader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v7.1.5',
            'version' => '7.1.5.0',
            'reference' => '5c03ee6369281177f07f7c68252a280beccba847',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typo3-console/libs' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '2e06dc49b9d5a3f775e0a4e346646ffe5a181463',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
